# Page settings
baseurl = "localhost:1313"
# Page settings
#baseurl = "https://dbenjamintraining.com"
title = "D Benjamin Training LLC - CDL and ELDT Driver Training in Monmouth County, Ocean County, and Surrounding Areas, NJ"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "David Benjamin"
  description = "D Benjamin Training LLC offers CDL and ELDT Driver Training for Class A, B, and C Licenses, Passenger & School Bus Endorsements, and Air Brake Training in Monmouth County, Ocean County, and Surrounding Areas, NJ."
  email = "f/xpzenzbw"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "D Benjamin Training LLC"
    home = "Home"
    work = "Courses"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

  # Hero section
  [params.hero]
    title = "Drive Your Future."
    subtitle = "Expert CDL - ELDT Driver Training in Monmouth, Ocean County & Nearby Areas, NJ - Comprehensive Training for the New Federal ELDT Requirements"

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Class A, B, and C Licenses"
    description = "Get professional training for your Class A, B, and C Commercial Driver's License and open up new opportunities in the transportation industry."
    url = "#"
    #button = "Learn More"
    icon = "icon-graduation"
    img = "img_class_b_license.jpg"

  [[params.intro.item]]
    title = "Passenger & School Bus Endorsements"
    description = "Become a certified bus driver with our passenger and school bus endorsement training, ensuring safety and compliance on the road."
    url = "#"
    #button = "Learn More"
    icon = "icon-bus"
    img = "img_passenger_school_bus.jpg"

  [[params.intro.item]]
    title = "Air Brake Training"
    description = "Master the operation and maintenance of air brake systems with our hands-on training in the comfort of your air brake equipped vehicle."
    url = "#"
    #button = "Learn More"
    icon = "icon-settings"
    img = "img_air_brake_training.jpg"

  [params.intro.video]
    enable = false

  # Work section (Courses)
  [params.work]
    enable = true
    title = "Courses"
    description = "Our comprehensive training programs are designed to help you gain the skills and knowledge needed for a successful career in the transportation industry, including dump trucks, school buses, box trucks, and rolloffs."

  # Testimonials section
  [params.testimonials]
    enable = false

  # Services section
  [params.services]
    enable = false

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "D Benjamin Training LLC is committed to providing high-quality CDL and ELDT Driver Training for Class A, B, and C Licenses in Monmouth County, Ocean County, and Surrounding Areas, NJ. Our experienced instructors ensure that every student receives personalized attention and guidance to achieve their goals."

  # Counters section
  [params.counters]
    enable = false

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = "Interested in our training programs? Get in touch with us and we'll be happy to assist you."

    details = [        ["icon-home", "Monmouth County, Ocean County, and Surrounding Areas, NJ"],
        ["icon-phone", "(732) 915-1665"],
        ["icon-envelope", "contact@dbenjamintraining.com"],
        ["icon-globe", '<a href="http://dbenjamintraining.com" target="_blank">dbenjamintraining.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; DBenjamin Training. All Rights Reserved.'
    links = [
        ["icon-google", "#google"],
        ["icon-facebook", "https://www.facebook.com/groups/739707993752621"]
      ]